version: "3.7"
services:

  webserver:
    container_name: esp32
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
